apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        name: mysql
        cost-center: mcm
        cost-center-code: mcm-101
        department: Reliance Industries
        project: WK_Project1
        app: AthenaApp
        env: Dev
        created_by: Developer
    spec:
      containers:
      - name: mysql
        image: mysql
        resources:
          limits:
            memory: "200Mi"
            cpu: 200m
          requests:
            memory: "100Mi"
            cpu: 100m
        ports:
        - containerPort: 3306
        env:
           - name: MYSQL_ROOT_PASSWORD
             value: paswrd