apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        name: mysql
        cost-center: mcm
        cost-center-code: mcm-101
        department: RelianceIndustries
        project: WK_Project1
        application: AthenaApp
        app: mysql
        env: Dev
        created_by: Developer
    spec:
      containers:
      - name: mysql
        image: mysql
        resources:
          limits:
            memory: "500Mi"
            cpu: 500m
          requests:
            memory: "500Mi"
            cpu: 500m
        ports:
        - containerPort: 3306
        env:
           - name: MYSQL_ROOT_PASSWORD
             value: paswrd