apiVersion: v1
kind: Secret
metadata:
    name: app-secret
    labels:
        name: app-secret
        cost-center: mcm
        cost-center-code: mcm-101
        department: RelianceIndustries
        project: WK_Project1
        application: Labelapp
        env: Prod
        created_by: Developer
data:
    DB_Host: bXlzcWw=
    DB_User: cm9vdA==
    DB_Password: cGFzd3Jk
