apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-webapp-mysql
spec:
  selector:
    matchLabels:
      app: simple-webapp-mysql
  replicas: 1
  template:
    metadata:
      labels:
        name: simple-webapp-mysql
        cost-center: mcm
        cost-center-code: mcm-101
        department: RelianceIndustries
        project: WK_Project1
        application: AthenaApp
        app: simple-webapp-mysql
        env: Dev
        created_by: Developer
    spec:
      containers:
      - name: simple-webapp-mysql
        image: kodekloud/simple-webapp-mysql
        resources:
          limits:
            memory: "500Mi"
            cpu: 500m
          requests:
            memory: "500Mi"
            cpu: 500m
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: app-secret-volumes
          mountPath: "/opt/app-secret-volumes"
          readOnly: true
        envFrom:
          - secretRef:
              name: app-secret
      volumes:
        - name: app-secret-volumes
          secret:
            secretName: app-secret