kind: Service
apiVersion: v1
metadata:
  name: webapp-service
  labels:
    app: AthenaApp
    name: simple-webapp-mysql
    cost-center: mcm
    cost-center-code: mcm-101
    department: Reliance Industries
    project: WK_Project1
    env: Dev
    created_by: Developer
spec:
  selector:
    name: simple-webapp-mysql
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
